#!/usr/bin/env bash
#checks if file exists
file="iacta"
#checks if file exists
if [ ! -e "$file" ]; then
	echo "File not found"
	exit 1
fi
#displays third line of file
line=$(head -n 3 iacta | tail -n 1)
echo "$line"
