#!/usr/bin/env bash
#displays the PID, along with the process name, of processes whose name contain the word bash
#For the first iteration: bash PID is 4404 and that the 3-show_your_bash_pid_made_easy script PID is 4555
#For the second iteration: bash PID is 4404 and that the 3-show_your_bash_pid_made_easy script PID is 4557
for pid in $(pgrep bash); do
	echo "$pid bash"
done
