#!/usr/bin/env bash
#displays To infinity and beyond indefinitely
#In between each iteration of the loop, add a sleep 2
#sleep 2 pauses execution for 2 seconds
# Trap Ctrl+C (SIGINT) to perform cleanup before exiting
trap 'cleanup_function' INT

cleanup_function() {
	echo "Terminated"
	exit 0
}
while true; do
	echo "To infinity and beyond"
	sleep 2
done
